name: Push commit
on: workflow_dispatch
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: |
          git config --global user.name 'eliot-pitman-va'
          git config --global user.email 'pitman_eliot@bah.com'
          git pull
          echo "hello" > report.txt
      - name: Commit report
        run: |
          git add .
          git commit -am "Automated report"
          git push
