name: Push commit
on: workflow_dispatch
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS }}
          aws-region: us-east-1
      - name: authenticate
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{secrets.CREDENTIALS_TOKEN}}
      - name: Create report file
        run: |
          url=$(aws s3 presign s3://practicebah/IMG_4141.jpg --expires-in 604800)
          echo "$url"
          echo "$url" > report.txt
      - name: Commit report
        run: |
          git add .
          git commit -am "Automated report"
          git push
